server:
  port: 8083

spring:
  application:
    name: timeMarks
  datasource:
    url: jdbc:mysql://localhost:3306/timemarksdb
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}